version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: taxi_app
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
        networks:
            - laravel
        environment:
            - MYSQL_HOST=db
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
        depends_on:
            - db
        restart: unless-stopped

    web:
        image: nginx:alpine
        container_name: taxi_web
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "1080:80"
        networks:
            - laravel
        depends_on:
            - app
        restart: unless-stopped

    db:
        image: mysql:9
        container_name: taxi_db
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - "3306:3306"
        networks:
            - laravel
        restart: unless-stopped

networks:
    laravel:
        name: taxi
        driver: bridge
